school/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_, name='login'),
    path('logout/', views.logout_, name='logout'),
    path('director/', views.index_director, name='home_director'),
    path('director/estudiantes/', views.leer_estudiantes, name='list_estudiantes'),   
    path('estudiante/', views.index_estudiante, name='home_estudiante'),
    path('profesor/', views.index_profesor, name='home_profesor'),
    path('director/usuario/crear', views.crear_usuario, name='crear_usuario')
    
]

stoMngr/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('school.urls')),
]

school/models.py
from django.db import models
from django.contrib.auth.models import Group, User
import datetime as dt
import statistics as stats

class Usuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rol = models.ForeignKey(Group, default=None, on_delete=models.CASCADE)
    num_id = models.CharField(max_length=11, unique=True)
    fec_nac = models.DateField()

    class Meta:
        permissions = [
            ('is_teacher', 'Docente'),
            ('is_student', 'Estudiante'),
            ('is_director', 'Directivo')
        ]

    def __str__(self):
        return "%s %s " %(self.user.first_name, self.user.last_name)

class Curso(models.Model):
    grado_CHOICES = [
        ('0', 'Transición'),
        ('1', 'Primero'),
        ('2', 'Segundo'),
        ('3', 'Tercero'),
        ('4', 'Cuarto'),
        ('5', 'Quinto'),
        ('6', 'Sexto'),
        ('7', 'Séptimo'),
        ('8', 'Octavo'),
        ('9', 'Noveno'),
        ('10', 'Décimo'),
        ('11', 'Undécimo')
    ]
    grado = models.CharField(max_length=2, choices=grado_CHOICES, default='0', unique=True)

    def __str__(self):
        grado_str = 'N/A'
        for i in self.grado_CHOICES:
            if(self.grado == i[0]):
                grado_str = i[1]
        return grado_str

class Grupo(models.Model):
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=2)
    dir_grupo = models.OneToOneField(Usuario, on_delete=models.CASCADE)

    def __str__(self):
        return '%s - %s' %(self.curso, self.nombre)   
    
class Matricula(models.Model):
    estudiante = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    curso = models.ForeignKey(Grupo, on_delete=models.CASCADE)
    estado = models.BooleanField(default=False)

    def __str__(self):
        return "%s Matriculado en el Curso: %s" %(self.estudiante, self.curso)

class Asignatura(models.Model):
    profesor = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return '%s -- Profesor: %s' %(self.nombre, self.profesor)

class Horario(models.Model):
    dias = (
        ('L', 'Lunes'),
        ('M', 'Martes'),
        ('Mi', 'Miercoles'),
        ('J', 'Jueves'),
        ('V', 'Viernes')
    )
    grupo = models.ForeignKey(Grupo, on_delete=models.CASCADE)
    asignatura = models.ForeignKey(Asignatura, on_delete=models.CASCADE)
    dia = models.CharField(max_length=2, choices=dias, default='L')
    hora = models.TimeField()

    def __str__(self):
        return "Asignatura: %s -- %s %s" %(self.asignatura, self.dia, self.hora)  

class Calificacion(models.Model):
    matricula = models.ForeignKey(Matricula, on_delete=models.CASCADE)
    asignatura = models.ForeignKey(Asignatura, on_delete=models.CASCADE)
    nota_1 = models.IntegerField()
    nota_2 = models.IntegerField()
    nota_3 = models.IntegerField()
    nota_4 = models.IntegerField()

    def nota_final(self):
        nota = (self.nota_1 + self.nota_2 + self.nota_3 + self.nota_4) / 4
        return nota  
  

    
    

school/forms.py
from django import forms
from django.db.models.base import Model
from django.forms import fields
from django.forms.models import ModelForm
from django.contrib.auth.models import Group
from .models import *

class UsuarioForm(ModelForm):
    nombre = forms.CharField(max_length=40, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nombre Completo'
    }))
    apellido = forms.CharField(max_length=60, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Apellidos'
    }))
    email = forms.EmailField(max_length=80, required=False, widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Correo Electrónico'
    }))
    rol = forms.ModelChoiceField(queryset=Group.objects.all(), widget=forms.Select(attrs={
        'class': 'form-select',
    }))
    num_id = forms.CharField(max_length=11, widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': 'Documento de Identidad',
        'min': '10000000',
        'max': '99999999999'
    }))
    fec_nac = forms.DateField(widget=forms.DateInput(attrs={
        'type': 'date',
        'class': 'form-control'
    }))

    class Meta:
        model = Usuario
        fields = ['rol', 'num_id', 'fec_nac'] 

school/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout 
from django.urls import reverse
from django.contrib.auth.models import User, Group, Permission
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from .forms import *

def login_(request):
    if request.method == 'POST':
        username = request.POST.get('inputUser')
        password = request.POST.get('inputPassword')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse('home'))
        else:
            return HttpResponse('Error en el usuario')

    else:
        return render(request, 'accounts/login.html')

@login_required(login_url='/login/')
def logout_(request):
    logout(request)
    return HttpResponseRedirect(reverse('login'))

@login_required(login_url='/login/')
def home(request):
    user = request.user
    if user.has_perm('school.is_student'):
        return HttpResponseRedirect(reverse('home_estudiante'))
    elif user.has_perm('school.is_teacher'):
        return HttpResponseRedirect(reverse('home_profesor'))
    elif user.has_perm('school.is_director'):
        return HttpResponseRedirect(reverse('home_director'))
    else:
        return HttpResponse('No tiene acceso')

@permission_required('school.is_director')
def index_director(request):
    return render(request, 'director/index.html')

@permission_required('school.is_student')
def index_estudiante(request):
    return render(request, 'estudiante/index.html')

@permission_required('school.is_teacher')
def index_profesor(request):
    return render(request, 'profesor/index.html')

@permission_required('school.is_director', login_url='/login/')
def crear_usuario(request):
    if request.method == 'POST':
        form = UsuarioForm(request.POST)        
        if form.is_valid():
            first_name = request.POST.get('nombre')
            last_name = request.POST.get('apellido')
            email = request.POST.get('email')
            username = request.POST.get('num_id')
            rol = request.POST.get('rol')
            grupo = Group.objects.get(id = rol)
            user = User.objects.create_user(username, email, username, first_name=first_name, last_name=last_name)
            user.save()
            usuario = form.save(commit=False)
            usuario.user = user
            usuario.save()
            user.groups.add(grupo)
            messages.success(request, 'Usuario Guardado correctamente')
            return HttpResponseRedirect(reverse('crear_usuario'))
        else:
            error = form.errors
            messages.error(request, error)
            return HttpResponseRedirect(reverse('crear_usuario'))
    else:
        form = UsuarioForm()
        context = {'form': form}
        return render(request, 'director/crear_usuario.html', context)

@permission_required('school.is_director', login_url='/login/')
def leer_estudiantes(request):
    grupo = Group.objects.get(id=1)
    estudiantes = grupo.user_set.all()    
    context = {'estudiantes': estudiantes}
    return render(request, 'director/list_estudiantes.html', context)

school/templates/Estudiante/formEstudiante.html
{% extends 'modal.html' %}

{% block modal_title %} Crear Estudiante {% endblock modal_title %}

{% block modal_body %}
<form id="formEstudiante">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_nombre">Nombre:</label>
        {{ form.nombre }}
    </div>
    <div class="form-group">
        <label for="id_apellidos">Apellidos:</label>
        {{ form.apellidos }}
    </div>
    <div class="form-group">
        <label for="id_num_id">Identificación:</label>
        {{ form.num_id }}
    </div>
    <div class="form-group">
        <label for="id_fec_nac">Fecha de Nacimiento:</label>
        {{ form.fec_nac }}
    </div>   
</form>
{% endblock modal_body %}

{% block modal_button %}
<button type="button" onclick="formEstudiante()" class="btn btn-primary">Guardar</button>
{% endblock modal_button %} 

school/templates/Estudiante/index.html
{% extends 'layout.html' %}

{% block main %}

<p>Soy un Estudiante</p>
                
{% endblock main %}

school/templates/accounts/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>School Mng | Login </title>
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/65eb220159.js" crossorigin="anonymous"></script>   
    <meta name="theme-color" content="#7952b3">

    <!-- Custom styles for this template -->
    <link href="{% static 'school/css/login.css' %}" rel="stylesheet">
  </head>
  <body class="text-center">
    
    <main class="form-signin">
        <form action="{% url 'login' %}" method="POST">
            {% csrf_token %}
            <i id="icon" class="mb-4 fas fa-school fa-8x"></i>            
            <h1 class="h3 mb-3 fw-normal">Acceso</h1>
            <label for="inputUser" class="visually-hidden">Usuario</label>
            <input type="text" name="inputUser" id="inputUser" class="form-control" placeholder="Usuario" required autofocus>
            <label for="inputPassword" class="visually-hidden">Contraseña</label>
            <input type="password" name="inputPassword" id="inputPassword" class="form-control" placeholder="Password" required>
            <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Recuérdame
            </label>
            </div>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Ingresar</button>
            <p class="mt-5 mb-3 text-muted">&copy; 2020</p>
        </form>
    </main>   
  </body>
</html>

school/templates/director/crear_usuario.html
{% extends 'layout.html' %}
{% block style %}

{% endblock style %} 
{% block menu %}
    {% include 'director/menu.html' %}
{% endblock menu %}

{% block main %}
    <div class="card">
        <div class="card-header container-fluid">
            <div class="row">
                <div class="col-sm-10">
                    <h5>Agregar Estudiantes</h5>
                </div>               
            </div>                    
        </div>                      
        <div class="card-body">            
            {% if messages %}
                {% include 'mensajes.html' %}                                   
            {% endif %}                
            <form id="formUsuario" action="{% url 'crear_usuario' %}" method="POST">
                {% csrf_token %}
                <div class="row mb-3">
                    <label for="id_nombre" class="col-sm-2 col-form-label">Nombres:</label>
                    <div class="col-sm-10">
                        {{form.nombre}}
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_apellido" class="col-sm-2 col-form-label">Apellidos:</label>
                    <div class="col-sm-10">
                        {{form.apellido}}
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_email" class="col-sm-2 col-form-label">E-Mail:</label>
                    <div class="col-sm-10">
                        {{form.email}}
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_rol" class="col-sm-2 col-form-label">Rol:</label>
                    <div class="col-sm-10">
                        {{form.rol}}
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_num_id" class="col-sm-2 col-form-label">Doc. Identidad:</label>
                    <div class="col-sm-10">
                        {{form.num_id}}
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_fec_nac" class="col-sm-2 col-form-label">Fecha de Nac.:</label>
                    <div class="col-sm-10">
                        {{form.fec_nac}}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>           
        </div>
    </div>  
                        
{% endblock main %}

{% block script %}

{% endblock script %}

school/templates/director/index.html
{% extends 'layout.html' %}

{% block menu %}
{% include 'director/menu.html' %}
{% endblock menu %}

{% block main %}

<p>Soy un Directivo</p>
                
{% endblock main %}

school/templates/director/list_estudiantes.html
{% extends 'layout.html' %}
{% block style %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap5.min.css"/> 
{% endblock style %} 
{% block menu %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'list_estudiantes' %}">Estudiante</a>
</li>
{% endblock menu %}

{% block main %}
    <div class="card">
        <div class="card-header container-fluid">
            <div class="row">
                <div class="col-sm-10">
                    <h5>Estudiantes</h5>
                </div>
                <div class="col-sm-2 float-right">
                    <a href="{% url 'crear_usuario' %}" class="btn btn-success" style="margin-left: 1em">Agregar Estudiante</a>
                </div>
            </div>                    
        </div>                      
        <div class="card-body">             
            <table id="estudiantes" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Email</th>
                        <th>Último Acceso</th>
                        <th>Creación</th>
                    </tr>
                </thead>
                <tbody>
                    {% for estudiante in estudiantes %}
                        <td>{{estudiante.first_name}}</td>
                        <td>{{estudiante.last_name}}</td>
                        <td>{{estudiante.email}}</td>
                        <td>{{estudiante.last_login}}</td>
                        <td>{{estudiante.date_joined}}</td>                    
                    {% endfor %}                    
                </tbody>                
            </table>
            
        </div>
    </div>  
                        
{% endblock main %}

{% block script %}
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.23/datatables.min.js"></script>
<script>
    $(document).ready(function() {
        $('#estudiantes').DataTable();
    } );
</script>
{% endblock script %}

school/templates/director/menu.html
<li class="nav-item">
    <a class="nav-link" href="{% url 'list_estudiantes' %}">Estudiantes</a>
</li>

school/templates/grupo/crear.html
{% extends 'layout.html' %}
{% load static %}

{% block title%} Grupo | Crear {% endblock %}

{% block style %}

{% endblock style %}

{% block menu %}

{% endblock menu %}

{% block main %}
<div class="card">
    <div class="card-header">
        <h3 class="page-section-heading text-center text-uppercase text-secondary mb-0">Crear Grupo</h3>
    </div>
    <div class="card-body">
        <form id="formGrupo">
            {% csrf_token %}            
            <div class="row mb-3">
                <label for="id_curso" class="col-sm-1 col-form-label">Curso:</label>
                <div class="col-sm-10">
                    {{ formGrupo.curso }}
                </div>
                <div class="col-sm-1">
                    <button id="btnCurso" type="button" class="btn">
                        <i class="fas fa-plus-circle"></i>
                    </button>
                </div>
            </div>
            <div class="row mb-3">
                <label for="id_nombre" class="col-sm-1 col-form-label">Nombre:</label>
                <div class="col-sm-10">
                    {{ formGrupo.nombre }}
                </div>                
            </div>
            <div class="row mb-3">
                <label for="id_dir_grupo" class="col-sm-1 col-form-label">Dir. Grupo:</label>
                <div class="col-sm-10">
                    {{ formGrupo.dir_grupo }}
                </div>
                <div class="col-sm-1">
                    <button id="btnProfesor" type="button" class="btn">
                        <i class="fas fa-plus-circle"></i>
                    </button>
                </div>
            </div>
            <button type="button" onclick="formularioGrupo()" class="btn btn-primary">Guardar</button>            
        </form>        
    </div>
</div>

{% endblock main %}

{% block script %}
<script>
    function formularioCurso(){
        formulario = $('#formGrado').serialize();        
        url = "{% url 'crear_curso' %}";
        gestionForm(url, formulario)
    }
    function formularioProfesor(){
        formulario = $('#formProfesor').serialize();        
        url = "{% url 'crear_profesor' %}";
        gestionForm(url, formulario)
    }
    function formularioGrupo(){
        url = "{% url 'crear_grupo' %}";
        formulario = $("#formGrupo").serialize();            
        gestionForm_nm(url, formulario); 
    }

    $(function() {         
        $("#btnCurso").click(function(){ 
            url = "{% url 'crear_curso' %}";         
            ejecutarModal(url);                 
        });
        $("#btnProfesor").click(function(){
            url = "{% url 'crear_profesor' %}";
            ejecutarModal(url);
        });                    
    });
</script>
    
{% endblock script %}

school/templates/grupo/formCurso.html
{% extends 'modal.html' %}

{% block modal_title %} Crear Curso {% endblock modal_title %}

{% block modal_body %}
<form id="formGrado">
    {% csrf_token %}
    <div class="row mb-3">
        <label for="" class="col-sm-2 col-form-label">Grado:</label>
        <div class="col-sm-10">
            {{ formCurso.grado }}
        </div>
    </div>
       
</form>
{% endblock modal_body %}

{% block modal_button %}
<button type="button" onclick="formularioCurso()" class="btn btn-primary">Guardar</button>
{% endblock modal_button %} 

school/templates/home.html
{% extends 'layout.html' %}
{% load static %}
{% block style %} {% endblock style %}

{% block menu %}
    <a class="nav-link" href="#">Matriculas</a>
{% endblock menu %}

{% block main %}
    Main
{% endblock main %}

school/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} {% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'school/assets/img/favicon.ico' %}" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Mukta:wght@200&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/65eb220159.js" crossorigin="anonymous"></script>
    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
        body {
            padding-top: 5rem;
          }
    </style>   
    {% block style %} {% endblock style %}    
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">School Manager</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>                                        
                    {% block menu %}
                    {% endblock menu %}
                </ul>
                <span class="navbar-text">                 
                {% if user.is_authenticated %}                    
                    Hola {{ user.first_name }}!
                    <a href="{% url 'logout' %}">Cerrar Sesión</a>
                {% endif %}    
                </span>
            </div>          
        </div>       
    </nav>
    <main class="container">
        <div class="starter-template py-5 px-3">
            {% block main %}
                
            {% endblock main %}
        </div>
    </main>      
    {% block modal %}
    <div class="modal" id="modal" tabindex="-1" role="dialog">
    
    </div>
    {% endblock modal %}
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="{% static 'school/js/script.js' %}"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>     
    {% block script %} {% endblock script %}
</body>
</html>

school/templates/matricula/crear.html
{% extends 'layout.html' %}
{% load static %}

{% block title%} Matricula | Crear {% endblock %}
  
{% block style %}

{% endblock style %}

{% block menu %}

{% endblock menu %}

{% block main %}
<div class="card">
    <div class="card-header">
        <h3 class="page-section-heading text-center text-uppercase text-secondary mb-0">Crear Matricula</h3>
    </div>
    <div class="card-body">
        <form action="">
            <div class="row mb-3">
                <label for="id_estudiante" class="col-sm-1 col-form-label">Estudiante:</label>
                <div class="col-sm-10">
                    {{ formMatricula.estudiante }}
                </div>
                <div class="col-sm-1">
                    <button type="button" id="btnEstudiante" class="btn">
                        <i class="fas fa-plus-circle"></i>
                    </button>
                </div>
            </div>
            <div class="row mb-3">
                <label for="id_curso" class="col-sm-1 col-form-label">Curso:</label>
                <div class="col-sm-10">
                    {{ formMatricula.curso }}
                </div>
                <div class="col-sm-1">
                    <a class="btn" href="{% url 'crear_grupo' %}"><i class="fas fa-plus-circle"></i></a>
                </div>
            </div>
            <div class="row mb-3">
                <div class="mb-3">
                    <div class="form-check form-switch">
                        {{ formMatricula.estado }}
                        <label class="form-check-label" for="id_estado">Estado</label>
                    </div>    
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Sign in</button>
        </form>
        
    </div>
</div>

{% endblock main %}


{% block script %}
<script>    
    function formEstudiante(){
        formulario = $('#formEstudiante').serialize();
        url = "{% url 'crear_estudiante' %}";
        gestionForm(url, formulario)
    }

    $(function() {         
        $("#btnEstudiante").click(function(){ 
            url = "{% url 'crear_estudiante' %}";         
            ejecutarModal(url);                 
        });      
    });
</script>
{% endblock script %}

school/templates/matricula/index.html
{% extends 'layout.html' %}

{% block title %} Matriculas {% endblock title %}
   
{% block style %}
     <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
{% endblock style %}

{% block menu %}

{% endblock menu %}

{% block main %}
<div class="card">
    <div class="card-header">
        <h3 class="page-section-heading text-center text-uppercase text-secondary mb-0">Matriculas</h3>
    </div>
    <div class="card-body">
        <table  id="table_id" class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Estudiante</th>
                    <th>Curso</th>
                    <th>Dir. Grupo</th>
                    <th>Estado</th>
                </tr>
            </thead>
            <tbody>
                {% for matricula in matriculas %}
                <tr>
                    <td>{{ matricula.id }}</td>
                    <td>{{ matricula.estudiante }}</td>
                    <td>{{ matricula.curso.curso}} {{ matricula.curso.nombre}}</td>
                    <td>{{ matricula.curso.dir_grupo}}</td>
                    <th>{{ matricula.estado }}</th>
                </tr>        
                {% endfor %}                
            </tbody>    
        </table>

        <a href="{% url 'crear_matricula' %}" class="btn btn-primary">Crear</a>
    </div>
</div>
{% endblock main %}

{% block script %}
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>
    <script>
    $(document).ready( function () {
        $('#table_id').DataTable();
    } );
    </script>
{% endblock script %}

school/templates/mensajes.html
{% for mensaje in messages %}
    <div class="alert {{ mensaje.tags }} alert-dismissible fade show" role="alert">                                   
        {{ mensaje}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %} 

school/templates/modal.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">
                {% block modal_title %} {% endblock modal_title %}
            </h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">            
            {% block modal_body %} {% endblock modal_body %}                
        </div>
        <div class="modal-footer">            
            {% block modal_button %} {% endblock modal_button %}                
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
    </div>
</div>
    

school/templates/profesor/formProfesor.html
{% extends 'modal.html' %}

{% block modal_title %} Crear Profesor {% endblock modal_title %}

{% block modal_body %}
<form id="formProfesor">
    {% csrf_token %}
    <div class="row mb-3">
        <label for="id_nombre" class="col-sm-2 col-form-label">Nombre:</label>
        <div class="col-sm-10">
            {{ formProfesor.nombre }}
        </div>
    </div>
    <div class="row mb-3">
        <label for="id_apellidos" class="col-sm-2 col-form-label">Apellidos:</label>
        <div class="col-sm-10">
            {{ formProfesor.apellidos }}
        </div>
    </div>
    <div class="row mb-3">
        <label for="id_num_id" class="col-sm-2 col-form-label">ID:</label>
        <div class="col-sm-10">
            {{ formProfesor.num_id }}
        </div>
    </div>
       
</form>
{% endblock modal_body %}

{% block modal_button %}
<button type="button" onclick="formularioProfesor()" class="btn btn-primary">Guardar</button>
{% endblock modal_button %} 

school/templates/profesor/index.html
{% extends 'layout.html' %}

{% block main %}

<p>Soy un Profesor</p>
                
{% endblock main %}